services:
  - type: web
    name: demo
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci && npm run build:server:prod && NODE_OPTIONS=--max-old-space-size=2048 npm run build:client:prod
    startCommand: npm --prefix server run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: NODE_ENV
        value: production
      - key: SERVER_HTTP_URL
        value: https://demo.onrender.com
      - key: SERVER_WS_URL
        value: wss://demo.onrender.com
